sudo: required

env:
  global:
    - DOCKER_IMAGE_NAME=anybox/caddy
  matrix:
    - VERSION=0.10.10
    - VERSION=0.10.9

services:
  - docker

install: true

# use a docker early version as multi stage docker build require
# docker >= 17.05
# https://docs.docker.com/engine/userguide/eng-image/multistage-build/
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - docker build --pull -t $DOCKER_IMAGE_NAME -f Dockerfile .
  - docker run -d -p 666:80 --name caddyserver $DOCKER_IMAGE_NAME

script:
  - docker ps | grep -q $DOCKER_IMAGE_NAME
  - sleep 2
  - curl "http://127.0.0.1:666"

after_success:
  - if [ ! -z "$TRAVIS_PULL_REQUEST" ]; then docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD && docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$VERSION && docker push $DOCKER_IMAGE_NAME:$VERSION; fi
